const ActionType = {
  CHANGE_HOME_ICON_COLOR: 'CHANGE_HOME_ICON_COLOR',
  CHANGE_WATCHLIST_ICON_COLOR: 'CHANGE_WATCHLIST_ICON_COLOR',
  CHANGE_DISCOVER_ICON_COLOR: 'CHANGE_DISCOVER_ICON_COLOR',
  CHANGE_NAVSIDE_TRUE: 'CHANGE_NAVSIDE_TRUE',
  CHANGE_NAVSIDE_FALSE: 'CHANGE_NAVSIDE_FALSE',
  ADD_KEYWORD: 'ADD_KEYWORD',
  ADD_DETAIL_MOVIE: 'ADD_DETAIL_MOVIE',
  ADD_DETAIL_GENRE: 'ADD_DETAIL_GENRE',
  ADD_DISCOVER_MOVIELIST: 'ADD_DISCOVER_MOVIELIST',
  ADD_MOVIE_GENRE_FILTER: 'ADD_MOVIE_GENRE_FILTER',
  ADD_MOVIE_RESULTS: 'ADD_MOVIE_RESULTS',
}

export default ActionType
